# Generated by Django 5.2.5 on 2025-11-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_dealerreview_car_year_dealerreview_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='name',
            new_name='dealer_name',
        ),
    ]
