# Generated by Django 5.2.5 on 2025-11-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_rename_name_dealer_dealer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerreview',
            old_name='dealer',
            new_name='dealer_name',
        ),
        migrations.RemoveField(
            model_name='dealerreview',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='dealerreview',
            name='reviewer_name',
        ),
    ]
