# Generated by Django 5.2.5 on 2025-11-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_dealerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerreview',
            name='car_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerreview',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealerreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
